### ISSUE TITLE
Uncaught exception 'Exception' with message 'Incorrect credentials. Access denied or incorrect parameters.

### ISSUE THREAD

**Issue by HorselessName** [iKnowITWorks/Creamy#1]
/var/www/html/php/DatabaseConnectorFactory.php:110\nStack trace:\n#0 /var/www/html/php/SessionHandler.php(60): creamy\\DatabaseConnectorFactory->getDatabaseConnectorOfType('MySQL')\n#1 /var/www/html/php/APIHandler.php(31): creamy\\SessionHandler->__construct()\n#2 /var/www/html/index.php(33): require_once('/var/www/html/p...')\n#3 {main}\n  thrown in /var/www/html/php/DatabaseConnectorFactory.php on line 110

How do i fix this error?

**Comment by mmixx** [comment]
I don't think this error is for Creamy... I think it's for a different one... Anyways, based on that error... It was a wrong DB credentials...
